on:
    push: {}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cmake ninja-build clang libelf-dev

            - name: Configure CMake
              run: |
                  mkdir build && cd build
                  cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release

            - name: Build project
              run: |
                  cd build
                  cmake --build .
